#!/bin/bash

export PATH=/home/parumon/perl5/perlbrew/perls/perl-5.18/bin:$PATH

APPDIR=/home/parumon/hcmpl-stream

case $1 in
        start)
                plackup -s Twiggy -E production --port 80 >/dev/null 2>&1 &
                ;;
        stop)
                pkill -TERM -f plackup
                ;;
        *)
                echo "usage: ./server {start|stop}"
                ;;
esac
exit 0

