#!/bin/bash

export PATH=/home/parumon/perl5/perlbrew/perls/perl-5.18/bin:$PATH

APPDIR=/home/parumon/hcmpl-stream
USER=parumon

case $1 in
        start)
                su $USER -c "carton exec -- start_server --port=80 --interval=5 --pid-file=$APPDIR/hcmplstream.pid -- plackup -Ilib -s Twiggy -E production >/dev/null 2>&1 &"
                ;;
        stop)
                su $USER -c "kill -TERM `cat $APPDIR/hcmplstream.pid`"
                ;;
        restart)
                su $USER -c "kill -HUP `cat $APPDIR/hcmplstream.pid`"
                ;;
        *)
                echo "usage: ./server {start|stop|restart}"
                ;;
esac
exit 0

